apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: mern
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6cm9vdEBtb25nby1zZXJ2aWNlOjI3MDE3L2Zvb2RtYXRlP2F1dGhTb3VyY2U9YWRtaW4=
