apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mern
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:     # Use hostPath only for development/minikube
    path: "/mnt/data/mongo"
