export interface Food {
    _id?: string; // Optional for creation, will be generated by MongoDB
    name: string;
    description: string;
    image?: string;
    sizes: FoodSize[];
    category: string;
    rating?: number; // Should be between 0-5 when provided
    available?: boolean;
    createdAt?: Date; // Will be automatically set by the schema
    updatedAt?: Date; // Will be automatically set by the schema
  }
  
  // For more type safety with size options:
  export interface FoodSize {
    name: string;
    price: number;
  }

  export interface Category{
    _id?:string
    name: string;
    icon?: string;
    createdAt: Date;
    updatedAt: Date;
  }